# Generated by Django 2.1.7 on 2019-03-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('profiles', '0004_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupData',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.Group')),
                ('description', models.TextField(blank=True)),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.Domain')),
            ],
        ),
    ]
