# Generated by Django 2.1.7 on 2019-03-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20190311_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupdata',
            name='description',
        ),
    ]
