# Generated by Django 2.1.7 on 2019-03-06 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectgroup',
            name='id',
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='projects.Project'),
        ),
    ]
