# Generated by Django 2.1.7 on 2019-03-09 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190306_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroup',
            name='group_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='project_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='projects.Project'),
        ),
    ]
