# Generated by Django 2.1.7 on 2019-03-10 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190310_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='group_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Group'),
        ),
    ]
