# Generated by Django 2.1.7 on 2019-03-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190310_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='group_id',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
