# Generated by Django 2.1.7 on 2019-03-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190310_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='group_id',
            new_name='group',
        ),
    ]
