# Generated by Django 2.1.7 on 2019-03-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('projects', '0008_auto_20190310_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Group')),
            ],
        ),
    ]
