# Generated by Django 2.1.7 on 2019-03-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='group_id',
            new_name='group',
        ),
    ]
