# Generated by Django 2.1.7 on 2019-03-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_reviewer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewer_id',
            new_name='reviewer',
        ),
    ]
