# Generated by Django 2.1.7 on 2019-04-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20190311_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rubric1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rubric10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rubric11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rubric12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rubric13',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rubric14',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rubric2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rubric3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rubric4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rubric5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rubric6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rubric7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rubric8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rubric9',
            field=models.IntegerField(default=0),
        ),
    ]
